### ISSUE TITLE
Removing modal from dom removes all instances 

### ISSUE THREAD

**Issue by jamilalisgandarov** [humaan/Modaal#102]
I am using selectize.js inside modal and initialize it inside modal. After closing modal just because all elements removed instance of selectize also is removed. So it s not working.

https://selectize.github.io/selectize.js/

**Comment by danhumaan** [comment]
Hi @jamilalisgandarov can you please provide an example of the issue you're having so we can help debug it? I believe I understand, but your exact setup might be different to my own approach. Once you're able to provide some more context, and code examples, we might be able to help you figure out a solution if you haven't already.

**Comment by danhumaan** [comment]
Closing this due to age, and lack of context and examples to the issue.
