### ISSUE TITLE
Modaal instagram, poping up problem

### ISSUE THREAD

**Issue by faradaytrs** [humaan/Modaal#106]
You can check it out on my website https://test.globus-furniture.com/#gallery 
Click on any image in "Furniture Heaven" block, modaal frame appears, but when you close and open another one, it can not to appear, although background gets darker and "close button" also works. I don't know why it happens, but that's a big problem.
![image](https://user-images.githubusercontent.com/3426470/41708763-2ab2e570-754a-11e8-89fb-0f3c6ad6e04e.png)
It looks like that, when it doesn't work. It should appear after loading, but it never happens.

**Comment by danhumaan** [comment]
Thanks for raising the issue @faradaytrs, I spent a little time this morning looking at this (and the quality issue in #95) a little more closely and have rolled out a fix for this. Grab the [latest copy](https://github.com/humaan/Modaal/releases/tag/v0.4.1) if you want to fix your build.

**Comment by faradaytrs** [comment]
Thank you very much
