### ISSUE TITLE
The display in the image does not work.

### ISSUE THREAD

**Issue by OlegOsokin** [humaan/Modaal#108]
The display in the image does not work.
What a bug, I enclose the code below.
![2018-07-09 15 14 56](https://user-images.githubusercontent.com/37975505/42449891-12741610-838b-11e8-904d-cc5c016bd801.png)
![2018-07-09 15 15 01](https://user-images.githubusercontent.com/37975505/42449892-1293b9c0-838b-11e8-84f7-8f1b389369b0.png)
![2018-07-09 15 15 10](https://user-images.githubusercontent.com/37975505/42449893-12b0ca10-838b-11e8-8704-11572f773072.png)
![2018-07-09 15 15 25](https://user-images.githubusercontent.com/37975505/42449894-12d17cec-838b-11e8-9c83-34494529df49.png)

**Comment by danhumaan** [comment]
Hey @OlegOsokin - thanks for raising this issue, a new release has just been rolled out which addresses and resolved this issue.
