### ISSUE TITLE
Open modaal from element inside iframe

### ISSUE THREAD

**Issue by hirschferkel** [humaan/Modaal#118]
Hi there,

thanxs for the great library. 
Is there a way to open modaal from an element e.g. a button inside an <object> element?
I load an svg inside an object and this svg should be opened by modaal but the triggering button should be within the svg? 

Haven't found a way to solve this...

Thanks for your help.

Best, hirschferkel

**Comment by danhumaan** [comment]
hi @hirschferkel, there is nothing built into Modaal to handle this, you will need to write your own JS to handle that kind of action.

I don't see this being a feature we'll build into the plugin either as it's so unique, so i'm going to close this ticket. Thanks

**Comment by hirschferkel** [comment]
hi @danhumaan,

thanks for your answer. I did not expect to implement this kiind of action to your code. But as I do not have any idea of jQuery but JS I do not know how to call the modal function from Javascript.
Do you have any hint how I can call the modaal from JS?
I know how to call the rigth element, but not how to pass the arguments to the jQuery...
Thanks for any help, hirschferkel

**Comment by hirschferkel** [comment]
The reason why it did not work was that the iframe was not completely loaded, while jQuery tried to attach the function. As `$(document).ready(function(){}` did not work, the workaround was to initialize it with

```
#$( window ).on( "load",function() {
$("#mainContent").contents().find("IDofDIVelement").modaal({});
});
```
Unfortunately after the modaal overlay gets closed, the functionallity vasnishes. Trying to find a way, now, to keep it on the element...

**Comment by hirschferkel** [comment]
The problem is that modaal injects the code which was wrapped and as it is an iframe-html it takes time to get loaded again. So modaal fires the after-close function bt the iframe is not ready.
The callback delay doesn't handle this problem as the iframe-content will load after it was inserted back from modaal...
Any idea, how I can re-attach the click-event to the iframe-element?

**Comment by hirschferkel** [comment]
O.K. i got it work:

```
$( window ).on( "load",function() {
$("#iframeID").contents().find("#IDofDIVelement").modaal({
content_source: '#modalwrapper',
overlay_close: true,
after_close: function reattach(){
reload();
}
});
});

function reload(){
      var length = $("#iframeID").contents().find("#IDofDIVelement").length;
      // The following will log 1 to the console, as the paragraph exists.
      if (length == 0) {
      	setTimeout(function(){ reload()}, 500);
      }
      else{
$("#iframeID").contents().find("#IDofDIVelement").modaal({
content_source: '#modalwrapper',
overlay_close: true,
after_close: function reattach(){
reload();
}
});
}
}
```

**Comment by hirschferkel** [comment]
O.k. it doesn not work as soon as someone changes something dynamically within the content_source e.g. visibility of the trigger button.
Even the binding of the click function gets lost this way... and if there are more than on iframe available it's not possible to work on.
