### ISSUE TITLE
.bind() vs. .on()

### ISSUE THREAD

**Issue by peterh-capella** [humaan/Modaal#16]
I notice you use .bind() for the keyboard events, but use .on() for the click events. Just wondering if there is something you've noticed about how the methods perform that made you decide to use the different methods?

**Comment by mynamesleon** [comment]
In the jQuery version used in the demo there is functionally no difference between `.bind` and `.on,` as `.bind` just passes the arguments to the `.on` method. The relevant section in the jQuery code base is:

```javascript
jQuery.fn.extend({
	bind: function(types, data, fn) {
		return this.on(types, null, data, fn);
	},
	unbind: function(types, fn) {
		return this.off(types, null, fn);
	}
});
```

**Comment by peterh-capella** [comment]
I suspected as much, which is what made the usage a little confusing. My guess is that it represents the plug-in being developed over a period of time (as .on() is a later addition to the jQuery library) and/or by a team of developers who have individual styles.

**Comment by cbotman** [comment]
Heya, yeah different methods are unintentional on our part. 

It's worth making consistent. Given bind is deprecated now, so should use on everywhere.

Regards,
Chris

**Comment by cbotman** [comment]
This is done and will be included in the next release, thanks. :)
