### ISSUE TITLE
Holding down tab causes the tab scope to break from the modal content

### ISSUE THREAD

**Issue by dropddesigns** [humaan/Modaal#2]
Tabbing through slowly seems to maintain the tab scope to within the modal content and address bar but when I held down tab, it breaks out of the modal content and I can start tabbing through the main web content that should not be in focus.

Browser: Google Chrome 50.0.2661.75 m

**Comment by danhumaan** [comment]
Hi @dropddesigns thanks for raising this issue, we'll investigate and work in an appropriate a resolution soon.

**Comment by cbotman** [comment]
This is now fixed. :)
