### ISSUE TITLE
Npm or Bower installation

### ISSUE THREAD

**Issue by Kepler-22b** [humaan/Modaal#20]
I think it would be nice to have possibility to install plugin via Bower and Npm package managers.

**Comment by jesseyuen** [comment]
Thank you @Kepler-22b for the suggestion! Modaal is now available via both Bower and [Npm](https://www.npmjs.com/package/modaal).

**Comment by danhumaan** [comment]
Re opening so we don't forget to update the readme 'instructions' section with information on these two package managers.

**Comment by danhumaan** [comment]
Updated readme.md with basic package management instructions
