### ISSUE TITLE
Focus styles for demo buttons

### ISSUE THREAD

**Issue by alastc** [humaan/Modaal#25]
A minor thing code-wise but an immediate blocker for some keyboard users:
The demo page (http://www.humaan.com/modaal/) doesn't have any keyboard-focus styles.
The dialogues themselves do (which is great) but it is hard to tell which one you are opening on the demo page.

I think it would be a matter of adding :focus to the :hover styles (e.g. demo.scss line 133), so the visual effect is there for keyboard users as well. 

There might be other places where it needs adding, but a search of 'hover' would probably find them.

Sorry, I'd fork it, change it, test it, and do a pull request, but by the time I've done that would be about 3 months from now!

**Comment by cbotman** [comment]
Hi Alastair, that's a very good point, thanks for that. Don't worry about a pull request, we can fix this up soon.

**Comment by AndrewArch** [comment]
+1 to @alastc - thanks @cbotman for taking on board directly

**Comment by cbotman** [comment]
I've put this change live now @alastc by doing as you suggested and added a :focus for anywhere we had :hover. 

Thanks for your help.
