### ISSUE TITLE
Is there any way to embed Facebook post like Instagram using post id?

### ISSUE THREAD

**Issue by ansarizeeshan** [humaan/Modaal#26]

**Comment by cbotman** [comment]
Hi @ansarizeeshan, there isn't, sorry. 

It looks like Facebook provide a plugin to care of this pretty well, so I'm not sure if it's something worth trying to add: https://developers.facebook.com/docs/plugins/embedded-posts

**Comment by ansarizeeshan** [comment]
Thanks @cbotman .
