### ISSUE TITLE
Another way for focus to escape modal (shift+tab as first action)

### ISSUE THREAD

**Issue by cbotman** [humaan/Modaal#28]
When a modal opens, if the first action you perform is to press shift+tab (i.e. previous link), it escapes the modal and focuses the first background link.

If your first action is to press tab, then you hit shift+tab twice, it doesn't then escape modal, so my guess is we're doing something when tab is pressed to restrict the focus, but we're not doing the same action on shift+tab.

**Comment by danhumaan** [comment]
A fix has been just been rolled out in the [latest release](https://github.com/humaan/Modaal/releases/latest) for this issue.
