### ISSUE TITLE
Remove JQuery dependency.

### ISSUE THREAD

**Issue by bklik** [humaan/Modaal#29]
Looking at your code, I don't really see why you're using JQuery. You could easily remove this dependency by replacing it with native JavaScript calls.

e.g.
var dom = document.body;
var element = document.querySelector('.class-name');
if(element.classList.contains('class-name') {};
element.addEventListener('click|keydown', function);
etc.

**Comment by pzi** [comment]
Dupe of #14

**Comment by bklik** [comment]
Derp
