### ISSUE TITLE
The image gallery allows me to try to view a non-existent image

### ISSUE THREAD

**Issue by dropddesigns** [humaan/Modaal#3]
When viewing the image gallery containing multiple images, I am able to use my arrow keys to navigate past the set of images available to get an empty carousel item page

![image](https://cloud.githubusercontent.com/assets/2650467/14692928/4cd472d6-078d-11e6-9071-50fbf47186a8.png)

**Comment by danhumaan** [comment]
Hi @dropddesigns - Thanks for raising this issue, we're looking into it and will push through a fix shortly.

**Comment by danhumaan** [comment]
Hi @dropddesigns this bug should be resolved now and is available in [v0.2.9](https://github.com/humaan/Modaal/releases/tag/v0.2.9)
