### ISSUE TITLE
Model content should include top-level text nodes

### ISSUE THREAD

**Issue by cbotman** [humaan/Modaal#34]
The Inline Content example (and others) are actually wrong at the moment. E.g.

```
<a href="#inline" class="inline">Show</a>
<div id="inline">
		Inline content goes here...
</div>
JS$(".inline").modaal();
```

This is because this line in create_basic:
`content = target.children().clone(true,true);`

Should be:
`content = target.contents().clone(true,true);`

Otherwise we're not grabbing top-level text nodes. Need to review the other modal creation methods for the same issue too.

Until this is fixed, an example like the above will show an empty modal. You can get around that by wrapping "Inline content goes here..." with an element. E.g. div, span, p

**Comment by danhumaan** [comment]
A fix has been just been rolled out in the [latest release](https://github.com/humaan/Modaal/releases/latest) for this issue.
