### ISSUE TITLE
Please dont touch body

### ISSUE THREAD

**Issue by AStaroverov** [humaan/Modaal#42]
Add ''overflow: hidden'' for body, in time open modal is bad, becouse its side effect for you independent  module and you can break someone else's layout.

**Comment by danhumaan** [comment]
Hi @AStaroverov, thanks for raising the issue - I understand your sentiment, however to control background scrolling this is the best method for us to address that.

If you need to avoid this property being added you can set `background_scroll` to `true`, and it won't add the property.

As a quick note on this point though, we've recently [made an adjustment](https://github.com/humaan/Modaal/commit/2e295e1ab50376477ef531c993d46c0a6940665c) which will be rolled out in milestone 0.3.0 soon, which replaces the direct css style in favour of controlling that via a class that get's added. This will give us greater flexibility while it's open and stopping/controlling scrolling than what was initially implemented.

**Comment by AStaroverov** [comment]
Oh! Thank you for the detailed answer!
