### ISSUE TITLE
Send focus to more semantic element on open

### ISSUE THREAD

**Issue by marcysutton** [humaan/Modaal#50]
The modal has focus management but when it opens, nothing is announced in Voiceover. If you send focus instead to the element with `role="dialog"` and an `aria-label`, those will be announced when the dialog opens. Or you could send focus to the close button–I've heard of people doing it either way. 

Here is a screenshot showing the wrapping dialog and DIV inside with `tabindex="0"`:
<img width="1391" alt="Dialog with browser dev tools open onto DOM" src="https://cloud.githubusercontent.com/assets/1045233/15717649/c84aed90-27dc-11e6-9b3b-331fa6489216.png">

You could move `tabindex` to the dialog element and change its value to `-1`, that way it won't be in the explicit tab order.

**Comment by danhumaan** [comment]
Hi @marcysutton firstly, thanks for taking the time to review this and raise the issue. I've flagged this ticket as a bug and assigned it to our next milestone so we can get it looked at, and a fix rolled out as soon as possible.

**Comment by danhumaan** [comment]
Hi @marcysutton, thanks again for your contribution. A fix has been just been rolled out in the [latest release](https://github.com/humaan/Modaal/releases/latest) for this issue.
