### ISSUE TITLE
Problem with jQuery-File-Upload plugin in modal

### ISSUE THREAD

**Issue by mojbenzcar** [humaan/Modaal#71]
I am trying the initialize the fileupload like 
```
$('.modal_selector').modaal({
        after_open: function () {
            $('.image_selector').fileupload();
        }
    });
```
but is not working and throwing 
`cannot call methods on fileupload prior to initialization; attempted to call method 'option'` error in console.

**Comment by danhumaan** [comment]
Hi @mojbenzcar, the error appears to be relating to fileupload rather than anything with Modaal. A quick google returned a number of different results - have you tried that first, or can you confirm this is an issue directly relating to Modaal?

**Comment by mojbenzcar** [comment]
thanks @danhumaan I was the fileupload plugin problem fixed it .
