### ISSUE TITLE
BUG> Example> Confirmation Modaal> not hooks

### ISSUE THREAD

**Issue by h2lsoft** [humaan/Modaal#77]
Hi,

with Chrome 55 example confirmation hooks is not working,
no alert return on confirm or cancel action.

**Comment by danhumaan** [comment]
hi @h2lsoft apologies for the delayed reply - are you still experiencing this issue? I had a short window of time time this morning to run a quick test and it seemed ok for me.

**Comment by danhumaan** [comment]
Hi @h2lsoft - Had some more time this morning to look into this one and had some difficulty replicating. Given this and the fact we're a few versions past 55 now I'm going to close this off unless you can provide more context and an example of this not working.
