### ISSUE TITLE
Improve jQuery support

### ISSUE THREAD

**Issue by danb-humaan** [humaan/Modaal#85]
Currently we only support jQuery 1.x, it'd be nice to expand this to 2.x and 3.x as they're newer.

Bonus points: make the core vanilla JS, but add the jQuery integration with a bridge, a la Isotope et al.

Bonus bonus points: make the core ES6 and use a transpiler to create an ES5-compatible build (I'd be happy to tackle this one).

**Comment by danhumaan** [comment]
Over the last 6-8 months, Modaal has been used extensively with jQuery v3 with no issues at all. I'm confident this is supported under v3.

For the moment I'll close this ticket as conversion to vanilla is much larger task we don't strictly have on the horizon, but is also covered in #14
