### ISSUE TITLE
Modaal with screen readers

### ISSUE THREAD

**Issue by alstoiche** [humaan/Modaal#87]
Hey guys, great work here. Just one little thing I've come across though. There's a little problem with how some screen readers look at markup with role="dialog", so markup inside it is ignored. I think it works in some readers, but not all.

https://github.com/nvaccess/nvda/issues/4493

We've been playing around with attaching a role="document" to one of the divs inside the dialog to get the SR to treat the div as containing document content. It looks like you could drop it on the "modaal-content-container" div. Just a thought!

Cheers,

Al

**Comment by danhumaan** [comment]
hi @alstoiche, thanks for sharing this finding with us. We've implemented the role dialog and tested again across chrome, ie and firefox with the latest NVDA. Please keep and eye on the next release for this inclusion.
