### ISSUE TITLE
Hard-coded “(Press escape to close)” in dialog title aria-label (l10n)

### ISSUE THREAD

**Issue by mirka** [humaan/Modaal#92]
There is a “(Press escape to close)” appended to the dialog title aria-label that can't be overridden through the `accessible_title` or the localization options added in https://github.com/humaan/Modaal/issues/41.
https://github.com/humaan/Modaal/blob/master/source/js/modaal.js#L358

**Comment by danhumaan** [comment]
Thanks @mirka good pickup.

**Comment by danhumaan** [comment]
This has been been addressed. The relevant hard coded text has been replaced with the `close_aria_label` option value so users who wish to overwrite it along with the close button label, can do so.

This will be rolled out in the next milestone release
